spring.application.name=travel
server.port=${PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=${DB_USER:postgres.ryybxlewunlxavehxjcp}
spring.datasource.password=${DB_PASSWORD:zaxscdvfbgnhmj}

mybatis.configuration.map-underscore-to-camel-case=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads/

supabase.url=${SUPABASE_URL:https://ryybxlewunlxavehxjcp.supabase.co}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.bucket-name=zyhan0911-createsOrg

spring.config.import=optional:classpath:application-dev.properties
